# Generated by Django 5.0.3 on 2024-04-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_phone_number_and_more'),
        ('users', '0002_user_phone_number'),
    ]

    operations = [
    ]
